# Generated by Django 3.0.4 on 2020-04-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_name', models.CharField(max_length=30)),
                ('course_id', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('course_date', models.CharField(max_length=10)),
                ('course_section', models.CharField(max_length=3)),
                ('course_semester', models.CharField(max_length=10)),
            ],
        ),
    ]
