# Generated by Django 3.0.4 on 2020-04-24 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_coursestudent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('startdate', models.DateTimeField()),
                ('enddate', models.DateTimeField()),
                ('assessment_id', models.CharField(max_length=9, primary_key=True, serialize=False, unique=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.CourseTeam')),
            ],
        ),
    ]
