# Generated by Django 3.0.4 on 2020-04-24 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_assessment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentOEQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('answer', models.CharField(max_length=250)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Assessment')),
            ],
        ),
    ]
