# Generated by Django 3.0.5 on 2020-04-27 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_assessmentoeq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursestudent',
            name='course',
        ),
        migrations.AddField(
            model_name='coursestudent',
            name='course',
            field=models.ManyToManyField(to='users.Course'),
        ),
        migrations.RemoveField(
            model_name='coursestudent',
            name='team',
        ),
        migrations.AddField(
            model_name='coursestudent',
            name='team',
            field=models.ManyToManyField(to='users.CourseTeam'),
        ),
    ]
