# Generated by Django 3.0.4 on 2020-04-28 03:27

from django.db import migrations, models
import django.db.models.deletion
import dynamic_forms.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200427_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('form', dynamic_forms.models.FormField()),
            ],
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', dynamic_forms.models.ResponseField()),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Survey')),
            ],
        ),
    ]
