# Generated by Django 3.0.5 on 2020-04-28 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_survey_surveyresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='course',
            field=models.CharField(choices=[('SWE', 'SWE'), ('CS1', 'CS1'), ('CS2', 'CS2'), ('Randomness', 'Randomness'), ('Logic', 'Logic')], default='SWE', max_length=20),
        ),
        migrations.AddField(
            model_name='survey',
            name='start_date',
            field=models.DateField(default='00/00/0000'),
        ),
        migrations.AddField(
            model_name='survey',
            name='submission_date',
            field=models.DateField(default='00/00/0000'),
        ),
    ]
