# Generated by Django 3.0.5 on 2020-04-29 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_survey_surveyresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentoeq',
            name='assessment',
        ),
        migrations.AddField(
            model_name='survey',
            name='course_survey',
            field=models.ManyToManyField(to='users.Course'),
        ),
        migrations.DeleteModel(
            name='Assessment',
        ),
        migrations.DeleteModel(
            name='AssessmentOEQ',
        ),
    ]
