# Generated by Django 3.0.5 on 2020-04-28 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200428_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='start_date',
            field=models.DateField(default='YYYY-MM-DD'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='submission_date',
            field=models.DateField(default='YYYY-MM-DD'),
        ),
    ]
