# Generated by Django 3.0.5 on 2020-04-28 22:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200428_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 28, 22, 30, 47, 831629)),
        ),
        migrations.AlterField(
            model_name='survey',
            name='submission_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 28, 22, 30, 47, 831655)),
        ),
    ]
