# Generated by Django 3.0.5 on 2020-04-28 22:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200428_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='start_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='survey',
            name='submission_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
