# Generated by Django 3.0.5 on 2020-04-28 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20200428_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='submission_date',
        ),
    ]
