# Generated by Django 3.0.5 on 2020-05-01 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200428_2057'),
        ('users', '0015_auto_20200428_2232'),
    ]

    operations = [
    ]
