# Generated by Django 3.0.6 on 2020-05-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_merge_20200501_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='course',
        ),
        migrations.RemoveField(
            model_name='courseinstructor',
            name='course',
        ),
        migrations.AddField(
            model_name='courseinstructor',
            name='course',
            field=models.ManyToManyField(to='users.Course'),
        ),
    ]
